name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.sha.outputs.sha_short }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: generate short commit hash
      id: sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  build:
    env:
      ORG: "parsertongue"
      IMAGE_NAME: "swagger-codegen-cli"
      TAG: "latest"
      DOCKERFILE: "Dockerfile"
      JAR_VERSION: "3.0.32"
    name: Publish images
    runs-on: "ubuntu-latest"
    needs: setup
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
    # Setup docker
    - name: Set up QEMU
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      continue-on-error: false
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{  secrets.DOCKERHUB_TOKEN }}
    - name: "Build AMD64 image"
      run: |
        wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/${JAR_VERSION}/swagger-codegen-cli-${JAR_VERSION}.jar -O swagger-codegen-cli.jar
        docker buildx build --platform=linux/amd64 -f ${DOCKERFILE} -t "${ORG}/${IMAGE_NAME}:amd64" .
    - name: "Test AMD64 image"
      run: |
        docker run "${ORG}/${IMAGE_NAME}:amd64" generate --help
    - name: "Build ARM64 image"
      run: |
        wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/${JAR_VERSION}/swagger-codegen-cli-${JAR_VERSION}.jar -O swagger-codegen-cli.jar
        docker buildx build --platform=linux/arm64 -f ${DOCKERFILE} -t "${ORG}/${IMAGE_NAME}:arm64" .
    - name: "Test ARM64 image"
      run: |
        docker run "${ORG}/${IMAGE_NAME}:arm64" generate --help
    - name: "Publish multi-platform docker image"
      if: github.ref == 'refs/heads/main'
      run: |
        wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/${JAR_VERSION}/swagger-codegen-cli-${JAR_VERSION}.jar -O swagger-codegen-cli.jar
        docker buildx build --platform=linux/amd64,linux/arm64 -f ${DOCKERFILE} --push -t "${ORG}/${IMAGE_NAME}:${TAG}" -t "${ORG}/${IMAGE_NAME}:${{ needs.setup.outputs.GIT_TAG }}"
        -t "${ORG}/${IMAGE_NAME}:${JAR_VERSION}" -t "${ORG}/${IMAGE_NAME}:${{ needs.setup.outputs.sha_short }}" .
    # see https://github.com/marketplace/actions/docker-hub-description#action-inputs
    - name: Update DockerHub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${ORG}/${IMAGE_NAME}
        # readme-filepath: ./path/to/README.md